#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
			local programName="serverName"

	        procd_open_instance
	        procd_set_param command /usr/bin/open-vpn-management -p "7505" -n $programName
	        procd_set_param pidfile /var/run/open-vpn-management.$programName.pid
			procd_set_param stdout 1
			procd_set_param stderr 1
        	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "open-vpn-management"
}

reload_service() {
	stop
	start
}
